web: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
worker: celery -A app.worker worker --loglevel=info --concurrency=4 -E
flower: celery -A app.worker flower --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
